### ISSUE TITLE
cycling aspect ratio is broken

### ISSUE THREAD

**Issue by ghost** [hl2guide/better-mpv-config#11]
when i press shift + p it says Unknown Property: 'video-aspect'

if i remove your configs, i can cycle aspect ratio again.

**Comment by hl2guide** [comment]
> when i press shift + p it says Unknown Property: 'video-aspect'
> 
> if i remove your configs, i can cycle aspect ratio again.

Sorry, I only just noticed this issue just now.

Thanks for reporting this.

I'll look into a fix in the next few versions. I may simply remove it from the config file.
