### ISSUE TITLE
missing set audio-delay 0

### ISSUE THREAD

**Issue by hovnatan** [hl2guide/better-mpv-config#12]
Shouldn't line https://github.com/hl2guide/better-mpv-config/blob/c1e20fce16f3b95c738dc7c9c45ba64eb2ff7d5b/mpv_v3/input.conf#L183 be` CTRL+n set audio-delay 0` since `CTRL+m` is used for `sub-delay` next in the config?

**Comment by hl2guide** [comment]
I imported that section from another repo (see credits).

I think the intention is that both `ctrl+n` and `ctrl+m` trigger the same action.

**Comment by hl2guide** [comment]
ah I see what you mean now. Okay should be fixed in version 1.3
