### ISSUE TITLE
CFL or Krig?

### ISSUE THREAD

**Issue by mysteryx93** [hl2guide/better-mpv-config#13]
Is there a reason Krig is used for chroma instead of CFL?

**Comment by hl2guide** [comment]
Does CFL have significant benefits? I'm open to changes.

**Comment by mysteryx93** [comment]
Seems to be the go-to filter now but I'm not the expert, do your research. Things keeps evolving all the time so it's hard to keep track.

**Comment by hl2guide** [comment]
Okay I'll consider this for a future update, but to be honest with you it's probably a long time off.
