### ISSUE TITLE
Question: Using profile= ?

### ISSUE THREAD

**Issue by 0pLuS0** [hl2guide/better-mpv-config#4]
Hello,

I'm using mpv in Linux and I typically click on a video in the file manager to play it with mpv. If I do this should I change ```profile=gpu-hq``` to the profile I want to use like ```[H60]``` as ```profile=H60```?

Because, what I did was remove all the profiles and I only kept ```[M60]``` and ```[H60]```, but I commented out all of ```[M60]```. So I wasn't sure if I can use the config like this when clicking on videos in the file manager to play them with ```profile=gpu-hq``` , or I need to change it to ```profile=H60```?

Here's my converted config file... THANKS

[config.txt](https://github.com/hl2guide/better-mpv-config/files/10430974/config.txt)

P.S. For now I changed it to ```profile=H60```.

**Comment by hl2guide** [comment]
the way mpv uses profiles is a cascade method so it would apply **gpu-hq** first and then **H60** for a video that matches dimensions and framerate.

**Comment by 0pLuS0** [comment]
Ok, because the Profiles has confused me a bit here.

Ok, So I'll leave it on profile=gpu-hq  and then leave [H60] uncommented to also use that.

See, I thought, when I do; ```mpv -profile help``` to see all the available Profiles I have to use, because [H60] is now listed in the ouput along with opengl-hq,
```
mpv -profile help
Available profiles:
	protocol.ytdl	ytdl
	protocol.https	https
	protocol.http	http
	extension.webm	webm
	extension.gif	gif
	H60	High - 1440p - 60 FPS
	enc-to-hp-slate-7	MP4 for HP Slate 7 (1024x600, crazy aspect)
	enc-to-nok-6300	3GP for Nokia 6300
	enc-to-nok-n900	MP4 for Nokia N900
	enc-to-dvdntsc	DVD-Video NTSC, use dvdauthor -v ntsc -a ac3+en (MUST be used with 4:3 or 16:9 aspect, and 720x480, 704x480, 352x480 or 352x240 resolution)
	enc-to-dvdpal	DVD-Video PAL, use dvdauthor -v pal -a ac3+en (MUST be used with 4:3 or 16:9 aspect, and 720x576, 704x576, 352x576 or 352x288 resolution)
	enc-f-webm	VP9 + Opus (for WebM)
	enc-f-mp4	H.264 + AAC (for MP4)
	enc-f-avi	MPEG-4 + MP3 (for AVI)
	enc-f-3gp	H.263 + AAC (for 3GP)
	enc-v-vp9	VP9 (libvpx)
	enc-v-vp8	VP8 (libvpx)
	enc-v-mpeg4	MPEG-4 Part 2 (FFmpeg)
	enc-v-mpeg2	MPEG-2 Video (FFmpeg)
	enc-v-h264	H.264 (x264)
	enc-v-h263	H.263 (FFmpeg)
	enc-a-opus	Opus (libopus or FFmpeg)
	enc-a-vorbis	Vorbis (libvorbis or FFmpeg)
	enc-a-mp3	MP3 (LAME)
	enc-a-ac3	AC3 (FFmpeg)
	enc-a-aac	AAC (libfdk-aac or FFmpeg)
	opengl-hq	
	sw-fast	
	low-latency	
	gpu-hq	
	encoding	
	libmpv	
	builtin-pseudo-gui	
	pseudo-gui	
	default	
```
that meant, I pick one and put it in ```profile=```. See now how I was confused? I've personally not spent a lot of time looking into/reading about the ```profile``` flag in mpv.

THANKS a lot for your time, it's greatly appreciated, and thanks for making these config files, they are great! 👍 💯
