### ISSUE TITLE
Question: Display & Video FPS - Stutter & Lag

### ISSUE THREAD

**Issue by 0pLuS0** [hl2guide/better-mpv-config#6]
Hello,

If I watch a video that's at 30fps and I have ```override-display-fps=60``` and ```profile-desc="High - 1080p - 60 FPS"``` there's a lot of stuttering I'll see in the video.

So for now I commented # out ```#override-display-fps=60``` and made the 1080p setting lines, (removing [fps<=?60]);

```profile-desc="High - 1080p"```
```ytdl-format=bestvideo[height<=?1080][vcodec!=?vp9]+bestaudio/best```

Forgive my ignorance here, I'm assuming there are two fps we deal with here, the display fps and what the video is recorded at?

So isn't it better not to define any fps in the config, so the videos just play at their recorded speeds?

By the way, I noticed you mentioned these configs aren't tested in Linux.

I'm running Slackware 15.0 with Openbox 3.6.1 and nvidia-driver-525.78.01.

I have a Ryzen 5 5600X with a EVGA FTW3 Ultra 3080, monitor is 1440p 165hz.

I get stutter and lag using the config for 1080p, which doesn't make sense I'd see stutter and lag with my hardware.

I'm attaching my modifided config, maybe you can tell me what I can try to adjust to make it run smoother?

[config.txt](https://github.com/hl2guide/better-mpv-config/files/11145183/config.txt)

THANKS

P.S. After posting this, I removed the Shaders lines. They were the ones causing the stuttter/lag in Linux. Here's a new modified config I'm using.

[config.txt](https://github.com/hl2guide/better-mpv-config/files/11145488/config.txt)

**Comment by hl2guide** [comment]
You are using the old legacy version that I no longer support or update.

**Comment by 0pLuS0** [comment]
Ok, well this didn't help me to understand if there is a newer version?

I looked at 1.0.8, 1.0.9, and 1.0.10 and I didn't see any complete mpv config settings, only partial settings.

THANKS

**Comment by hl2guide** [comment]
@0pLuS0 

Check out "mpv.v3.config.1.0.10.zip": [here](https://github.com/hl2guide/better-mpv-config/releases/tag/1.0.10)

I'm not sure if mpv v3 is out for Linux or not, check that [here](https://mpv.io/installation/)

Good luck

**Comment by 0pLuS0** [comment]
I've been using mpv for as long as it's been around in Linux.

This v3 thing, sounds more like some version for Windows, I've never seen or heard of any v3 ever for Linux.

Have you looked at the mpv GitHub repo before?

https://github.com/mpv-player/mpv

Every source code Linux version, since release has been on 0.x I'm now on the latest 0.35.1

I did look at 1.0.10 and I was scratching my head, wondering where all the options went, that were like in 1.0.7, if someone is suppose to put all those new changes now in the 1.0.7 config, because these are still options being used in Linux.

Looking at 1.0.10 made me wonder, is this all your using now in Windows, or these were suppose to then be added into the 1.0.7 config.

This is what I'm actually using in Linux right now that works.

[mpv.txt](https://github.com/hl2guide/better-mpv-config/files/11158344/mpv.txt)

**Comment by hl2guide** [comment]
v3 of mpv has sensible defaults that negate the need to have them in the config file.

I will be removing the legacy config file as it seems to be confusing people.

**Comment by 0pLuS0** [comment]
Can you tell me where you are seeing this v3 for mpv?

I wasn't aware there was this versioning... 

The 1.0.7 is not Legacy for the latest version of mpv under Linux, those are still vaild config options.

1.0.10 is the confusion, because I don't see that this is mentioned to be amended to 1.0.7.

In Linux 1.0.10 is not a complete config file, 1.0.7 is.

THANKS
