### ISSUE TITLE
[Q&A] can I use v3 conf on mpv v2?

### ISSUE THREAD

**Issue by bachig26** [hl2guide/better-mpv-config#9]
1. will there be any conflict using v3 conf on the mpv v2?

2. if so, what can I modify to solve it?

**Comment by hl2guide** [comment]
A1) Likely, you can try it out and then open up mpv's console (tilde `~` or `F1`).
A2) Any errors will be listed in red there. You can then comment out in `mpv.conf` to solve issues.
For more info please refer to: https://mpv.io/manual/stable/

**Comment by bachig26** [comment]
@hl2guide can you take a look this screenshot, and it showed me a issue with gpu as it seems slow.
I'll fix the missing keybinding later too.
in the second screenshot, it shows a audio underrun issue, it maybe a (as the video just started) buffering issue.

can you let me know will there any issue, i was planning to customize more with uosc and with other scripts along with it and config modifications.

### Screenshot
1. **Local Video**
![mpv_UuqtlY7P9r](https://github.com/hl2guide/better-mpv-config/assets/96393348/2677223f-541f-44c5-bdcf-dd6db6a728d3)

2. **URL Streaming**
![mpv_GgdGBgtRlI](https://github.com/hl2guide/better-mpv-config/assets/96393348/ea129c86-6cc5-41de-92e5-52bd3fdd8187)
